### ISSUE TITLE
Selection jumps to last row in all demos

### ISSUE THREAD

**Issue by ziobit** [wolf-table/table#1]
I tried the demo using the links provided, and both with Chromium-based and Firefox based engines, when I try to edit a cell and press 'enter', it jumps to the row 100th, the last one.
I don't think it's the intended / good behavior, right? It should stay on the same cell or maybe go to the right or 1 row below, not to the last. Or is there a reason behind it?

**Comment by myliang** [comment]
clone project to local
npm run dev

**Comment by sdmq** [comment]
package.json  修改

"dev": "webpack serve --config build/webpack.dev.js",
